# Site settings
title: overexposed
email: overexposed-blog@gmail.com
description: This is a collection of personal stories.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
