# Site settings
title: overexposed
email: overexposed-blog@gmail.com
description: This is a collection of personal stories.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://overexposed.herokuapp.com" # the base hostname & protocol for your site
permalink: /:categories/:title
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
gems: ['kramdown']
# stop Jekyll including your configuration in it’s generated site.
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
